import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0F1E] px-6 py-10 text-[#F1F5F9]">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="flex items-center gap-2 text-sm text-[#0EA5E9] hover:underline mb-8">
          <ArrowLeft size={16} /> Back
        </Link>

        <h1 className="text-3xl font-black mb-2">Terms of Service</h1>
        <p className="text-sm text-[#8A98AC] mb-8">Last updated: June 2026</p>

        <div className="flex flex-col gap-8 text-sm text-[#94A3B8] leading-relaxed">
          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Acceptance</h2>
            <p>
              By creating an account or using PaddleIQ, you agree to these Terms. If you do not
              agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Your Account</h2>
            <p>
              You are responsible for maintaining the security of your account and password. You
              must be at least 13 years old to use PaddleIQ. Provide accurate information when
              creating your account.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Acceptable Use</h2>
            <p>
              Use PaddleIQ only for lawful purposes. Do not attempt to reverse-engineer, scrape,
              or misuse the service. Do not upload content that is harmful, offensive, or violates
              others&apos; rights.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Your Data</h2>
            <p>
              You own your training data. By using PaddleIQ you grant us a limited licence to store
              and process your data to provide the service. See our{" "}
              <Link href="/legal/privacy" className="text-[#0EA5E9] underline">Privacy Policy</Link>
              {" "}for details.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Disclaimer</h2>
            <p>
              PaddleIQ is a training tool, not a medical device. Consult a qualified coach or
              physician before following any training advice generated by the app. We make no
              guarantees about performance improvements or race outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, PaddleIQ is provided &ldquo;as is&rdquo;
              without warranty. We are not liable for indirect, incidental, or consequential
              damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Changes</h2>
            <p>
              We may update these Terms. We will notify you of material changes via email or an
              in-app notice. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-[#F1F5F9] mb-2">Contact</h2>
            <p>
              Questions?{" "}
              <a href="mailto:support@paddleiq.app" className="text-[#0EA5E9] underline">
                support@paddleiq.app
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
